stages:
  - setup
  - build
  - deploy

before_script:
  - powershell -Command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force"

build:
  stage: build
  script:
    - npm install
    - npm run build
    - npm install vercel
    - powershell -Command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Restricted -Force"
    - vercel deploy