build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

deploy:
  stage: deploy
  script:
    - git remote set-url origin https://github.com/Ainzw0rth/frontend-cf-guru-sekolah.mu_deploy.git
    - git add .
    - git commit -m "push from recent frontend"
    - git push
  only:
    - master
