stages:
  - test
  - test2

variables:
  VERCEL_URL: https://vercel.com/ainzw0rth/frontend-cf-guru-sekolah-mu/settings
  VERCEL_TOKEN: UP1QNO8AV6zdrBEAsH9pPFhT

test: 
  stage: test
  image: node:14
  script: 
    - npm install

test2:
  stage: test2
  image: registry.vercel.io/vercel/vercel:latest
  script:
    - vercel --token $VERCEL_TOKEN --prod
  only:
    - dev